# Generated by Django 3.2.4 on 2023-10-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cuestion_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='cuestion_id',
            new_name='cuestion',
        ),
    ]
