# Generated by Django 3.2.4 on 2023-10-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cuestion_id_response_cuestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response',
            new_name='response2',
        ),
    ]
