# Generated by Django 3.2.4 on 2023-10-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_response_response_response2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='response2',
            new_name='response',
        ),
        migrations.AlterField(
            model_name='response',
            name='cuestion',
            field=models.IntegerField(),
        ),
    ]
