# Generated by Django 3.2.4 on 2023-10-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20231020_1916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cuestion',
            new_name='Pregunta',
        ),
        migrations.RenameModel(
            old_name='response',
            new_name='Respuesta',
        ),
    ]
