# Generated by Django 3.2.4 on 2023-10-23 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuestion', models.IntegerField()),
                ('response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('type_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('enrollment', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('middle_name', models.CharField(default='', max_length=30)),
                ('curp', models.CharField(default='', max_length=30, unique=True)),
                ('nss', models.CharField(default='', max_length=30, unique=True)),
                ('phone', models.CharField(default='', max_length=30)),
                ('mobile', models.CharField(default='', max_length=30)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='type_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usertype'),
        ),
    ]
